name: Build IP Domain Resolver Deb Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential dh-make devscripts

    - name: Create DEB package
      run: |
        mkdir -p ipdomain-resolver/usr/local/bin
        cp ipdomain-resolver.sh ipdomain-resolver/usr/local/bin/ipdomain-resolver
        chmod +x ipdomain-resolver/usr/local/bin/ipdomain-resolver

        mkdir -p ipdomain-resolver/DEBIAN
        echo "Package: ipdomain-resolver" > ipdomain-resolver/DEBIAN/control
        echo "Version: 1.0" >> ipdomain-resolver/DEBIAN/control
        echo "Section: utils" >> ipdomain-resolver/DEBIAN/control
        echo "Priority: optional" >> ipdomain-resolver/DEBIAN/control
        echo "Architecture: all" >> ipdomain-resolver/DEBIAN/control
        echo "Maintainer: MikeDev0ps <https://github.com/MikeDev0ps>" >> ipdomain-resolver/DEBIAN/control
        echo "Description: A script that processes IP addresses and performs DNS lookups." >> ipdomain-resolver/DEBIAN/control

        dpkg-deb --build ipdomain-resolver

    - name: Publish to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -X PUT -H "Authorization: token $GITHUB_TOKEN" \
        -H "Content-Type: application/octet-stream" \
        --data-binary @ipdomain-resolver.deb \
        "https://uploads.github.com/packages/MikeDev0ps/ipdomain-resolver/ipdomain-resolver_1.0_all.deb"

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0
        name: Release v1.0
        files: |
          ipdomain-resolver.deb
          ipdomain-resolver.sh
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
