name: Build IP Domain Resolver Deb Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential dh-make devscripts

      - name: Create DEB package
        run: |
          mkdir -p ipdomain-resolver/usr/local/bin
          cp ipdomain-resolver.sh ipdomain-resolver/usr/local/bin/ipdomain-resolver
          chmod +x ipdomain-resolver/usr/local/bin/ipdomain-resolver

          mkdir -p ipdomain-resolver/DEBIAN
          echo "Package: ipdomain-resolver" > ipdomain-resolver/DEBIAN/control
          echo "Version: 1.0" >> ipdomain-resolver/DEBIAN/control
          echo "Section: utils" >> ipdomain-resolver/DEBIAN/control
          echo "Priority: optional" >> ipdomain-resolver/DEBIAN/control
          echo "Architecture: all" >> ipdomain-resolver/DEBIAN/control
          echo "Maintainer: MikeDev0ps <https://github.com/MikeDev0ps>" >> ipdomain-resolver/DEBIAN/control
          echo "Description: A script that processes IP addresses and performs DNS lookups." >> ipdomain-resolver/DEBIAN/control

          dpkg-deb --build ipdomain-resolver

      - name: Create Release
        id: create_release
        uses: actions/create-release@v4
        with:
          tag_name: v1.0
          release_name: Release v1.0
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload deb package to Release
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ipdomain-resolver.deb
          asset_name: ipdomain-resolver.deb
          asset_content_type: application/vnd.debian.binary

      - name: Upload script to Release
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ipdomain-resolver.sh
          asset_name: ipdomain-resolver.sh
          asset_content_type: application/x-shellscript
